# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 247da26b712832dbea4f998d3ca10c6176db72b202266b2e53fd7930fb06a1de1d6ce814c1edff618956ee7edebac0eac7c88bb445f58fc77ca4112427b3036e

test:
  secret_key_base: 1ec0bc0fd14c0bfe1f81ec5b404d6097b555c1a7594ee26ab350ba52b71127b57b0bd57cbe629e0c8c16e3effc5fb4b7d1e117cf5ab5bfc9d5fb78757daae6bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
